#ifndef SCG_CLIENT_H
#define SCG_CLIENT_H

#pragma once

/* Auto-generated by cbindgen from the scg-client crate. Run `cargo build -p scg-client` to regenerate; do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Transport selector: Unix-domain socket.
 */
#define SCG_TRANSPORT_UDS 0

/**
 * Transport selector: shared memory.
 */
#define SCG_TRANSPORT_SHM 1

/**
 * Traffic class: best-effort / non-safety.
 */
#define SCG_CLASS_NORMAL 0

/**
 * Traffic class: safety-critical.
 */
#define SCG_CLASS_SAFETY 1

/**
 * Direction: application encrypts toward the upstream.
 */
#define SCG_DIRECTION_ENCRYPT 0

/**
 * Direction: application receives decrypted traffic (v1: unsupported).
 */
#define SCG_DIRECTION_DECRYPT 1

/**
 * Return code: success.
 */
#define SCG_OK 0

/**
 * Return code: generic failure (see [`scg_client_last_error`]).
 */
#define SCG_ERR -1

/**
 * Return code from [`scg_client_recv`]: no message within the timeout.
 */
#define SCG_TIMEOUT 1

/**
 * Opaque client handle. Created by [`scg_client_connect`], destroyed by
 * [`scg_client_close`].
 */
typedef struct ScgClientHandle ScgClientHandle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create an endpoint and connect its data plane.
 *
 * Returns a non-null handle on success, or null on failure (in which case a
 * message is written to `err_buf`, truncated to `err_len - 1` bytes plus a
 * terminating NUL).
 *
 * `mgmt_socket` may be null to use the default management socket path.
 *
 * # Safety
 * All pointers must be null or valid; `app_id` must be a valid C string.
 */
ScgClientHandle *scg_client_connect(const char *mgmt_socket,
                                    const char *app_id,
                                    int transport,
                                    int traffic_class,
                                    int direction,
                                    char *err_buf,
                                    uintptr_t err_len);

/**
 * Send one framed message.
 *
 * Returns [`SCG_OK`] or [`SCG_ERR`]. A `len` of 0 sends an empty frame.
 *
 * # Safety
 * `handle` must be a live handle; `data` must point to `len` readable bytes
 * (or may be null when `len == 0`).
 */
int scg_client_send(ScgClientHandle *handle,
                    uint32_t traffic_id,
                    const uint8_t *data,
                    uintptr_t len);

/**
 * Receive one framed message.
 *
 * On success returns [`SCG_OK`], sets `*traffic_id_out`, and allocates a
 * buffer into `*out_data` / `*out_len` that the caller must release with
 * [`scg_client_free_buf`]. Returns [`SCG_TIMEOUT`] if no message arrived
 * within `timeout_ms` (a negative `timeout_ms` blocks indefinitely), or
 * [`SCG_ERR`] on error.
 *
 * # Safety
 * `handle` must be a live handle; the out-pointers must be null or valid.
 */
int scg_client_recv(ScgClientHandle *handle,
                    uint32_t *traffic_id_out,
                    uint8_t **out_data,
                    uintptr_t *out_len,
                    int timeout_ms);

/**
 * Release a buffer previously returned by [`scg_client_recv`].
 *
 * # Safety
 * `data`/`len` must be exactly a pair produced by [`scg_client_recv`], passed
 * at most once.
 */
void scg_client_free_buf(uint8_t *data, uintptr_t len);

/**
 * Return the last error message recorded on `handle`, or null if none.
 *
 * The returned pointer is owned by the handle and valid until the next failed
 * call on it or until the handle is closed.
 *
 * # Safety
 * `handle` must be a live handle or null.
 */
const char *scg_client_last_error(const ScgClientHandle *handle);

/**
 * Deregister the endpoint and free the handle.
 *
 * Returns [`SCG_OK`] if the gateway acknowledged the close, else [`SCG_ERR`]
 * (the handle is freed either way).
 *
 * # Safety
 * `handle` must be a live handle (or null) and must not be used afterwards.
 */
int scg_client_close(ScgClientHandle *handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SCG_CLIENT_H */
